"""Create services table

Revision ID: 087bfbf08aec
Revises: 4cd74e74fbe7
Create Date: 2019-01-10 21:54:55.009835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '087bfbf08aec'
down_revision = '4cd74e74fbe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
      sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
      sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
      sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
      sa.Column('name', sa.String(length=255), nullable=False),
      sa.Column('base_url', sa.String(length=255), nullable=False),
      sa.Column('description', sa.String(length=255), nullable=False),
      sa.Column('is_active', sa.Boolean(), nullable=True),
      sa.PrimaryKeyConstraint('id'),
      mysql_charset='utf8mb4',
      mysql_collate='utf8mb4_unicode_ci',
      mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    # ### end Alembic commands ###
