"""Add user_id to tag table

Revision ID: 9c39e466aaeb
Revises: 9782f93091fb
Create Date: 2019-01-09 23:33:56.755896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c39e466aaeb'
down_revision = '9782f93091fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_tags', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_accounting_tag_user_id', 'account_tags', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_accounting_tag_user_id', 'account_tags', type_='foreignkey')
    op.drop_column('account_tags', 'user_id')
    # ### end Alembic commands ###
