"""Add foreign key on accounting tag item

Revision ID: 2a235399a9af
Revises: 2957beba60df
Create Date: 2019-01-01 18:02:57.854386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a235399a9af'
down_revision = '2957beba60df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_items', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_accounting_tag_id', 'account_items', 'account_tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_accounting_tag_id', 'account_items', type_='foreignkey')
    op.drop_column('account_items', 'tag_id')
    # ### end Alembic commands ###
