"""Create games_room

Revision ID: 5ac6b9d4c209
Revises: 9b952096cc92
Create Date: 2019-01-17 22:17:10.615300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ac6b9d4c209'
down_revision = '9b952096cc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('game_rooms',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('uuid', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('expire_at', mysql.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('game_rooms')
    # ### end Alembic commands ###
