"""Add user_id to item, category table

Revision ID: 4cd74e74fbe7
Revises: 74b9f6719701
Create Date: 2019-01-10 00:02:23.381754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cd74e74fbe7'
down_revision = '74b9f6719701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_accounting_cate_user_id', 'account_categories', 'users', ['user_id'], ['id'])
    op.add_column('account_items', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_accounting_item_user_id', 'account_items', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_accounting_item_user_id', 'account_items', type_='foreignkey')
    op.drop_column('account_items', 'user_id')
    op.drop_constraint('fk_accounting_cate_user_id', 'account_categories', type_='foreignkey')
    op.drop_column('account_categories', 'user_id')
    # ### end Alembic commands ###
