"""video table add thumb_nail

Revision ID: 30ed4db0f152
Revises: 86a4840b8386
Create Date: 2020-05-31 13:53:36.008658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30ed4db0f152'
down_revision = '86a4840b8386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumb_nail', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumb_nail')
    # ### end Alembic commands ###
