"""Add fallguys into category

Revision ID: fef4e2997e48
Revises: f283c0546274
Create Date: 2020-08-28 17:07:39.045000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef4e2997e48'
down_revision = 'f283c0546274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TABLE `videos` MODIFY COLUMN `category` enum('dota','pubg','fallguys','blog')")
    #
    # ### end Alembic commands ###

def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('videos', 'category', existing_type=sa.Enum('dota', 'pubg', 'blog'))
    # ### end Alembic commands ###
