"""Add piano into category

Revision ID: 0a5f2064e00c
Revises: fef4e2997e48
Create Date: 2020-11-10 17:35:23.942487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a5f2064e00c'
down_revision = 'fef4e2997e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TABLE `videos` MODIFY COLUMN `category` enum('dota','pubg','fallguys','blog', 'piano')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'category',
               existing_type=mysql.ENUM('dota', 'pubg', 'fallguys', 'blog', collation='utf8mb4_unicode_ci'),
               nullable=True)
    # ### end Alembic commands ###
