"""timeline rename message to content

Revision ID: 526d091cd5de
Revises: 79325a0cf63b
Create Date: 2020-06-19 16:48:26.823916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '526d091cd5de'
down_revision = '79325a0cf63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelines', sa.Column('content', sa.String(length=2000), nullable=False))
    op.drop_column('timelines', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelines', sa.Column('message', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2000), nullable=False))
    op.drop_column('timelines', 'content')
    # ### end Alembic commands ###
