"""timeline, comment change cloumn to is_removed

Revision ID: 71b262895a5b
Revises: 526d091cd5de
Create Date: 2020-06-19 17:02:39.248688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71b262895a5b'
down_revision = '526d091cd5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_removed', sa.Boolean(), nullable=True))
    op.drop_column('comments', 'is_active')
    op.add_column('timelines', sa.Column('is_removed', sa.Boolean(), nullable=True))
    op.drop_column('timelines', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelines', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('timelines', 'is_removed')
    op.add_column('comments', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('comments', 'is_removed')
    # ### end Alembic commands ###
