"""add catagory to video

Revision ID: ae9f2b71608c
Revises: a5015da86f94
Create Date: 2020-06-20 16:52:09.725532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9f2b71608c'
down_revision = 'a5015da86f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('category', sa.Enum('dota', 'pubg', 'blog'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'category')
    # ### end Alembic commands ###
