"""add timeline title

Revision ID: 79325a0cf63b
Revises: 3d67c90b506e
Create Date: 2020-06-19 16:44:46.609117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79325a0cf63b'
down_revision = '3d67c90b506e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelines', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('timelines', 'message',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timelines', 'message',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.drop_column('timelines', 'title')
    # ### end Alembic commands ###
