"""timeline, comment is_removed defalut value to False

Revision ID: a5015da86f94
Revises: 71b262895a5b
Create Date: 2020-06-19 17:30:19.356974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5015da86f94'
down_revision = '71b262895a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
