"""comment table add is_active

Revision ID: 95e82e06adb0
Revises: fe75aeca12a8
Create Date: 2020-06-18 18:02:52.520887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e82e06adb0'
down_revision = 'fe75aeca12a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_active')
    # ### end Alembic commands ###
