"""Add level to user table

Revision ID: 007b9cee0544
Revises: 68006d294976
Create Date: 2020-05-30 16:26:29.166262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '007b9cee0544'
down_revision = '68006d294976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True, default=2))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    # ### end Alembic commands ###
