"""add uuid to blog_posts 

Revision ID: 5974ce877b2c
Revises: 21f93775d003
Create Date: 2020-05-22 19:13:06.617900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5974ce877b2c'
down_revision = '21f93775d003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('uuid', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'uuid')
    # ### end Alembic commands ###
