"""video table add is_published column

Revision ID: 563c6ec512d2
Revises: 1b83f3409f0d
Create Date: 2020-05-30 19:21:38.068770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '563c6ec512d2'
down_revision = '1b83f3409f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'is_published')
    # ### end Alembic commands ###
