"""Add cover_img, blog_intro to BlogPostModel

Revision ID: ff8921fc845c
Revises: 5e6fdbb36f9f
Create Date: 2020-07-15 23:06:25.985407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8921fc845c'
down_revision = '5e6fdbb36f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('blog_intro', sa.Text(), nullable=False))
    op.add_column('blog_posts', sa.Column('cover_img', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'cover_img')
    op.drop_column('blog_posts', 'blog_intro')
    # ### end Alembic commands ###
