"""create lable bridge connection

Revision ID: 3e8dc6077a74
Revises: 0a5f2064e00c
Create Date: 2021-03-10 19:07:06.738156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e8dc6077a74'
down_revision = '0a5f2064e00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_unicode_ci',
                    mysql_engine='InnoDB'
                    )
    op.create_table('label_bridges',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('label_id', sa.Integer(), nullable=True),
                    sa.Column('blog_id', sa.Integer(), nullable=True),
                    sa.Column('video_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['blog_id'], ['blog_posts.id'], ),
                    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
                    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_unicode_ci',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('label_bridges')
    op.drop_table('labels')
    # ### end Alembic commands ###
