"""add hidden content post

Revision ID: c65eefa92794
Revises: 46e4c45dbc58
Create Date: 2021-09-07 10:16:36.985279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c65eefa92794'
down_revision = '46e4c45dbc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hidden_content',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('uuid', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_unicode_ci',
                    mysql_engine='InnoDB'
                    )
    op.create_table('hidden_content_bridges',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('hidden_content_id',
                              sa.Integer(), nullable=False),
                    sa.Column('blog_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['blog_id'], ['blog_posts.id'], ),
                    sa.ForeignKeyConstraint(['hidden_content_id'], [
                        'hidden_content.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_unicode_ci',
                    mysql_engine='InnoDB'
                    )
    op.add_column('blog_posts', sa.Column(
        'is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'is_hidden')
    op.drop_table('hidden_content_bridges')
    op.drop_table('hidden_content')
    # ### end Alembic commands ###
