"""Add video type sax

Revision ID: a5d2b6608ef2
Revises: 44fec5142e9f
Create Date: 2021-08-30 21:42:40.469366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5d2b6608ef2'
down_revision = '44fec5142e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'category',
                    existing_type=mysql.ENUM(
                        'dota', 'pubg', 'fallguys', 'blog', 'piano', collation='utf8mb4_unicode_ci'),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'category',
                    existing_type=mysql.ENUM(
                        'dota', 'pubg', 'fallguys', 'blog', 'piano', collation='utf8mb4_unicode_ci'),
                    nullable=True)
    # ### end Alembic commands ###
