"""Add video source model

Revision ID: 44fec5142e9f
Revises: 3e8dc6077a74
Create Date: 2021-08-30 12:51:25.426882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44fec5142e9f'
down_revision = '3e8dc6077a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_source',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(
                        'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('url', sa.String(length=255), nullable=False),
                    sa.Column('icon', sa.String(length=255), nullable=True),
                    sa.Column('video_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_unicode_ci',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_source')
    # ### end Alembic commands ###
